stages:
  - prod

default:
  image:
    name: "registry.werf.io/werf/werf:2-stable"
  before_script:
    - source "$(werf ci-env gitlab --as-file)"
  tags:
    - mukaev
    - canary

prod:
  stage: prod
  script:
    - werf converge
  environment:
    name: prod
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"
      when: manual