apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  - name: api-token
    valueFrom:
      secretKeyRef:
        name: rollout-token
        key: token
  metrics:
  - name: success-rate
    interval: 1m
    successCondition: result[0] >= 0.95
    failureLimit: 2
    provider:
      prometheus:
        address: https://prometheus.d8-monitoring:9090
        insecure: true
        headers:
          - key: Authorization
            value: "Bearer {{ args.api-token }}"
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code!~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]
          ))
