apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: nginx
spec:
  ingressClass: nginx
  inlet: HostPort
  enableIstioSidecar: true
  hostPort:
    httpPort: 80
    httpsPort: 443
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/worker
      operator: Exists
