---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollout
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app:prometheus-access
rules:
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheuses/http"]
  resourceNames: ["main", "longterm"]
  verbs: ["get","create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app:prometheus-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app:prometheus-access
subjects:
- kind: ServiceAccount
  name: rollout
  namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  name: rollout-token
  annotations:
    kubernetes.io/service-account.name: rollout
type: kubernetes.io/service-account-token
